version: "3.8"
services:

  # PHP service
  app:
    volumes:
      - ./:/var/www
    working_dir: /var/www/
    build: ./.docker/
#    entrypoint: /var/www/.docker/entrypoint.sh
    container_name: rsporteman-validator
    networks:
      - rsporteman

networks:
  rsporteman:
    driver: bridge